global:
  scrape_interval: 1s

scrape_configs:
  # make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # make Prometheus scrape itself for metrics.
  - job_name: 'eureka'
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka
