insert into messages values ('Hello')
insert into messages values ('JPA')
insert into STORE (category, item, stock) values ('books', 'Isbn100', 42)
insert into STORE (category, item, stock) values ('books', 'Isbn101', 4)
insert into STORE (category, item, stock) values ('books', 'Isbn102', 420)